version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "3040:9090"  # Prometheus web interface
    volumes:
      - prometheus_data:/prometheus  # Persistent storage
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro  # Config file
    networks:
      - custom_network

volumes:
  prometheus_data:

networks:
  custom_network:
    driver: bridge
